name: glucose_guardian
description: Mobile app for the Glucose Guardian platform
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0-444.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  avatar_glow: ^2.0.2
<<<<<<< HEAD
  dio: ^4.0.6
=======
>>>>>>> 68e6012 (Depend on avatar_glow)
  email_validator: ^2.1.17
  equatable: ^2.0.5
  fl_chart: ^0.55.2
  flutter_bloc: ^8.1.1
  flutter_otp_text_field: ^1.1.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  hive: ^2.2.3
  intl: ^0.18.0
  page_view_dot_indicator: ^2.1.0
  passwordfield: ^0.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_transparent.png
    - assets/cgm_icon.svg
    - assets/prescriptions_icon.svg
    - assets/syringe_icon.svg
    - assets/undraw_student.svg
    - assets/undraw_professor.svg
    - assets/undraw_err_eng.svg
    - assets/undraw_error.svg
