name: glucose_guardian
description: Mobile app for the Glucose Guardian platform
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=2.19.0-444.2.beta <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  awesome_dialog: ^3.0.2
  bloc: ^8.1.1
  dio: ^4.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^13.0.0
  flutter_overlay_loader: ^2.0.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  otp_text_field: ^1.1.3
  page_view_dot_indicator: ^2.1.0
  passwordfield: ^0.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_transparent.png
    - assets/cgm_icon.svg
    - assets/prescriptions_icon.svg
    - assets/syringe_icon.svg
    - assets/undraw_student.svg
    - assets/undraw_professor.svg
    - assets/undraw_err_eng.svg
    - assets/undraw_error.svg
