name: glucose_guardian
description: Mobile app for the Glucose Guardian platform
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies:
  email_validator: ^2.1.17
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  passwordfield: ^0.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_transparent.png
    - assets/cgm_icon.svg
